snippet:
  88f3d643-ca05-4dc0-a338-964390a39ce3:
    id: 88f3d643-ca05-4dc0-a338-964390a39ce3
    name: abc
    content:
      body: abc
  d0a5315e-494f-4760-8859-be42d3e26e8c:
    id: d0a5315e-494f-4760-8859-be42d3e26e8c
    name: false-ifUserInMeeting
    content:
      body:
        data: false
  97423a98-30c5-479d-8a34-0f7bfcf1ae7d:
    id: 97423a98-30c5-479d-8a34-0f7bfcf1ae7d
    name: code200
    content:
      body:
        code: 200
  7ef09c6c-f242-4549-aa28-51aa6244ce1d:
    id: 7ef09c6c-f242-4549-aa28-51aa6244ce1d
    name: data2EmptyArray
    content:
      body:
        $fixed data: []
breakpoint:
  'http://yapi.sankuai.com/mock/2841/api/getmeetings':
    - response
  'http://iamsrv.it.dev.sankuai.com/dc/qy/accounts/1/applyAccount/applied/page':
    - response
apiBindSnippet:
  'http://zoom.test.meituan.com/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
  'http://iamsrv.it.dev.sankuai.com/dc/qy/1/agent/blacklist/reasons': 97423a98-30c5-479d-8a34-0f7bfcf1ae7d
  'http://yapi.sankuai.com/mock/2841/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
  'http://lh:9081:9081/meeting/dataset/getCityBuildingAndFloor': 7ef09c6c-f242-4549-aa28-51aa6244ce1d
  'https://www.mocky.io/v2/5185415ba171ea3a00704eed': 97423a98-30c5-479d-8a34-0f7bfcf1ae7d
