snippet:
  88f3d643-ca05-4dc0-a338-964390a39ce3:
    id: 88f3d643-ca05-4dc0-a338-964390a39ce3
    name: abc
    content:
      body: abc
  d0a5315e-494f-4760-8859-be42d3e26e8c:
    id: d0a5315e-494f-4760-8859-be42d3e26e8c
    name: false-ifUserInMeeting
    content:
      body:
        data: false
  97423a98-30c5-479d-8a34-0f7bfcf1ae7d:
    id: 97423a98-30c5-479d-8a34-0f7bfcf1ae7d
    name: code200
    content:
      body:
        code: 200
  7ef09c6c-f242-4549-aa28-51aa6244ce1d:
    id: 7ef09c6c-f242-4549-aa28-51aa6244ce1d
    name: data2EmptyArray
    content:
      body:
        $fixed data: []
  fe550821-92a2-46c8-80ed-9047cbfa859f:
    id: fe550821-92a2-46c8-80ed-9047cbfa859f
    name: Inject Eruda
    content:
      body: !<tag:yaml.org,2002:js/function> |-
        function anonymous(body
        /*``*/) {
          return body.replace(/(<\/body>)/, '<script src="//cdn.jsdelivr.net/npm/eruda"></script><script>eruda.init();</script>$1')
        }
  f05e8851-d14f-4531-9dd7-8f941568e0e4:
    id: f05e8851-d14f-4531-9dd7-8f941568e0e4
    name: Inject Erra
    content:
      body: !<tag:yaml.org,2002:js/function> >-
        function anonymous(body

        /*``*/) {
        return body.replace(/(<\/body>)/, '<script
        src="http://localhost:1234/erra-portal.js"></script>$1')
        }
breakpoint:
  'http://yapi.sankuai.com/mock/2841/api/getmeetings':
    - response
  'http://iamsrv.it.dev.sankuai.com/dc/qy/accounts/1/applyAccount/applied/page':
    - response
apiBindSnippet:
  'http://zoom.test.meituan.com/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
  'http://iamsrv.it.dev.sankuai.com/dc/qy/1/agent/blacklist/reasons': 97423a98-30c5-479d-8a34-0f7bfcf1ae7d
  'http://yapi.sankuai.com/mock/2841/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
  'http://lh:9081:9081/meeting/dataset/getCityBuildingAndFloor': 7ef09c6c-f242-4549-aa28-51aa6244ce1d
  'http://lh:7001/zoom-manage-web/user/meeting-entry': f05e8851-d14f-4531-9dd7-8f941568e0e4
