SERVICE_CONFIG:
  httpPort: 3344
  httpsPort: 4455
snippet:
  735215e6-5c00-4443-8ce9-83d7382e9e02:
    id: 735215e6-5c00-4443-8ce9-83d7382e9e02
    name: Forward-Meituan
    when: !<tag:yaml.org,2002:js/regexp> /meituan.com/
    content:
      headers:
        host: www.mocky.io
      url: /v2/5185415ba171ea3a00704eed
    enabled: false
  6353c69c-e1e6-4b34-a61a-c44271fce483:
    id: 6353c69c-e1e6-4b34-a61a-c44271fce483
    name: Simple-Demo
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body:
        hello: Erra!
  fa48a039-7186-4308-b32a-21aa268fddc4:
    id: fa48a039-7186-4308-b32a-21aa268fddc4
    name: Mockjs-Random
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body:
        $mockjs hello: '@str'
  594f64b2-e795-4c15-9359-5da8e2b5c800:
    id: 594f64b2-e795-4c15-9359-5da8e2b5c800
    name: Include-Snippet
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body:
        code: 200
        $snippet include: Simple-Demo|6353c69c-e1e6-4b34-a61a-c44271fce483
  a1a16ba9-7fb8-4fd3-9fa2-cfac11301846:
    id: a1a16ba9-7fb8-4fd3-9fa2-cfac11301846
    name: Inject-Eruda
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      headers:
        content-security-policy: ''
      body: !<!expression> >-
        V.replace(/(<\/body>)/, '<script>window.define=undefined</script><script
        src="//cdn.bootcss.com/eruda/1.5.2/eruda.min.js"></script><script>eruda.init();</script>$1')
  4df3f3ae-7b3f-41fe-b62b-e34c58177eb9:
    id: 4df3f3ae-7b3f-41fe-b62b-e34c58177eb9
    name: Inject-Erra
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body: !<!expression> >-
        V.replace(/(<\/body>)/, '<script
        src="https://localhost:4455/erra/erra-portal.js"></script>$1')
breakpoint:
  'http://yapi.sankuai.com/mock/2841/api/getmeetings':
    - response
  'http://iamsrv.it.dev.sankuai.com/dc/qy/accounts/1/applyAccount/applied/page':
    - response
apiBindSnippet:
  'http://zoom.test.meituan.com/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
  'http://iamsrv.it.dev.sankuai.com/dc/qy/1/agent/blacklist/reasons': 97423a98-30c5-479d-8a34-0f7bfcf1ae7d
  'http://yapi.sankuai.com/mock/2841/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
  'http://lh:9081:9081/meeting/dataset/getCityBuildingAndFloor': 7ef09c6c-f242-4549-aa28-51aa6244ce1d
  'http://lh:7001/zoom-manage-web/user/meeting-entry': f05e8851-d14f-4531-9dd7-8f941568e0e4
  'http://lh:8890/access-permission': f05e8851-d14f-4531-9dd7-8f941568e0e4
  'http://iamsrv.it.dev.sankuai.com/dc/qy/1/pms/appInfo/host': 22938ccb-880d-4ce0-8d96-4a881d32aa94
  'https://zoom.test.meituan.com/zoom-manage-web/user/meeting-entry': f05e8851-d14f-4531-9dd7-8f941568e0e4
  'https://www.mocky.io/v2/5185415ba171ea3a00704eed': fa48a039-7186-4308-b32a-21aa268fddc4
  'http://i.meituan.com/': fe550821-92a2-46c8-80ed-9047cbfa859f
  'https://i.meituan.com/': fe550821-92a2-46c8-80ed-9047cbfa859f
  'https://www.baidu.com/': fe550821-92a2-46c8-80ed-9047cbfa859f
  'https://sh.meituan.com/': a1a16ba9-7fb8-4fd3-9fa2-cfac11301846
