snippet:
  88f3d643-ca05-4dc0-a338-964390a39ce3:
    id: 88f3d643-ca05-4dc0-a338-964390a39ce3
    name: abc
    content:
      body: abc
  d0a5315e-494f-4760-8859-be42d3e26e8c:
    id: d0a5315e-494f-4760-8859-be42d3e26e8c
    name: false-ifUserInMeeting
    content:
      body:
        data: false
        code: 200
        message: success
breakpoint: {}
apiBindSnippet:
  'http://zoom.test.meituan.com/api/ifUserInMeeting': d0a5315e-494f-4760-8859-be42d3e26e8c
