# ERRA服务配置，可指定 httpPort, httpsPort
SERVICE_CONFIG:
  httpPort: 3344
  httpsPort: 4455
snippet:
  fe550821-92a2-46c8-80ed-9047cbfa859f:
    id: fe550821-92a2-46c8-80ed-9047cbfa859f
    name: Inject Eruda
    content:
      headers:
        content-security-policy: ''
      body: !<tag:yaml.org,2002:js/function> |-
        function anonymous(body
        ) {
          return body.replace(/(<\/body>)/, '<script src="//cdn.bootcss.com/eruda/1.5.2/eruda.min.js"></script><script>eruda.init();</script>$1')
        }
    when: !<tag:yaml.org,2002:js/undefined> ''
  f05e8851-d14f-4531-9dd7-8f941568e0e4:
    id: f05e8851-d14f-4531-9dd7-8f941568e0e4
    name: Inject Erra
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body: !<tag:yaml.org,2002:js/function> |-
        function anonymous(body
        ) {
          return body.replace(/(<\/body>)/, '<script src="https://localhost:4455/erra/erra-portal.js"></script>$1') 
        }
  735215e6-5c00-4443-8ce9-83d7382e9e02:
    id: 735215e6-5c00-4443-8ce9-83d7382e9e02
    name: Forward-Meituan
    when: !<tag:yaml.org,2002:js/regexp> /meituan.com/
    content:
      headers:
        host: www.mocky.io
      url: !<tag:yaml.org,2002:js/function> |-
        function anonymous(
        ) {
        return '/v2/5185415ba171ea3a00704eed'
        }
    enabled: false
  6353c69c-e1e6-4b34-a61a-c44271fce483:
    id: 6353c69c-e1e6-4b34-a61a-c44271fce483
    name: Simple-Demo
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body:
        hello: Erra!
  fa48a039-7186-4308-b32a-21aa268fddc4:
    id: fa48a039-7186-4308-b32a-21aa268fddc4
    name: Mockjs-Random
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body:
        $mockjs hello: '@str'
  594f64b2-e795-4c15-9359-5da8e2b5c800:
    id: 594f64b2-e795-4c15-9359-5da8e2b5c800
    name: Include-Snippet
    when: !<tag:yaml.org,2002:js/undefined> ''
    content:
      body:
        code: 200
        $snippet include: Simple-Demo|6353c69c-e1e6-4b34-a61a-c44271fce483
breakpoint:
apiBindSnippet: